# Generated by Django 2.1.5 on 2019-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='12345678-0000-0000-123456789012', max_length=36)),
                ('major', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('dt_last', models.DateTimeField(auto_now_add=True)),
                ('dt_battery', models.DateTimeField(auto_now_add=True)),
                ('work_place_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=55)),
                ('login_pw', models.CharField(max_length=55)),
                ('name', models.CharField(default='unknown', max_length=127)),
                ('position', models.CharField(default='', max_length=33)),
                ('department', models.CharField(default='', max_length=33)),
                ('pNo', models.CharField(max_length=19)),
                ('pType', models.IntegerField(default=0)),
                ('push_token', models.CharField(default='unknown', max_length=255)),
                ('email', models.CharField(default='unknown', max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(default=0)),
                ('staff_id', models.IntegerField(default=-1)),
                ('staff_name', models.CharField(default='unknown', max_length=127)),
                ('staff_pNo', models.CharField(default='', max_length=19)),
                ('place_name', models.CharField(default='unknown', max_length=127)),
                ('contractor_id', models.IntegerField(default=-1)),
                ('contractor_name', models.CharField(default='unknown', max_length=127)),
                ('manager_id', models.IntegerField(default=-1)),
                ('manager_name', models.CharField(default='unknown', max_length=127)),
                ('manager_pNo', models.CharField(default='', max_length=19)),
                ('manager_email', models.CharField(default='', max_length=320)),
                ('order_id', models.IntegerField(default=-1)),
                ('order_name', models.CharField(default='unknown', max_length=127)),
                ('order_staff_id', models.IntegerField(default=-1)),
                ('order_staff_name', models.CharField(default='unknown', max_length=127)),
                ('order_staff_pNo', models.CharField(default='', max_length=19)),
                ('order_staff_email', models.CharField(default='', max_length=320)),
            ],
        ),
    ]
