# Generated by Django 2.1.5 on 2019-02-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(default='unknown', max_length=512),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login_pw',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pNo',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='staff',
            name='push_token',
            field=models.CharField(default='unknown', max_length=256),
        ),
    ]
