# Generated by Django 2.1.5 on 2019-02-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20190208_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('dt_android_upgrade', models.DateTimeField()),
                ('manager_id', models.IntegerField(default=0)),
                ('timeCheckServer', models.CharField(max_length=15)),
            ],
        ),
    ]
