# Generated by Django 2.1.5 on 2019-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='dt_battery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='dt_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dt_app_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dt_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
