# Generated by Django 2.1.5 on 2019-06-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20190507_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=127)),
                ('work', models.CharField(max_length=1024)),
            ],
        ),
    ]
