# Generated by Django 2.1.5 on 2019-06-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
