# Generated by Django 2.1.5 on 2019-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=38)),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('dt_last', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beacon_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('passer_id', models.IntegerField()),
                ('dt_begin', models.DateTimeField(auto_now_add=True)),
                ('RSSI_begin', models.IntegerField()),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=127)),
                ('work_start', models.CharField(default='', max_length=20)),
                ('working_time', models.CharField(default='', max_length=20)),
                ('work_start_alarm', models.CharField(default='', max_length=20)),
                ('work_end_alarm', models.CharField(default='', max_length=20)),
                ('bank', models.CharField(default='', max_length=20)),
                ('bank_account', models.CharField(default='', max_length=20)),
                ('work_id', models.IntegerField(default=-1)),
                ('work_id_2', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField()),
                ('customer_work_id', models.CharField(default='', max_length=127)),
                ('employee_id', models.IntegerField(default=-1)),
                ('employee_pNo', models.CharField(max_length=19)),
                ('dt_answer_deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passer_id', models.IntegerField()),
                ('is_in', models.IntegerField(default=10)),
                ('dt_reg', models.DateTimeField(blank=True, null=True)),
                ('dt_verify', models.DateTimeField(blank=True, null=True)),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passer_id', models.IntegerField()),
                ('action', models.IntegerField(default=10)),
                ('dt_in', models.DateTimeField(blank=True, null=True)),
                ('dt_in_verify', models.DateTimeField(blank=True, null=True)),
                ('dt_out', models.DateTimeField(blank=True, null=True)),
                ('dt_out_verify', models.DateTimeField(blank=True, null=True)),
                ('minor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNo', models.CharField(max_length=19)),
                ('pType', models.IntegerField(default=0)),
                ('push_token', models.CharField(default='', max_length=255)),
                ('employee_id', models.IntegerField(default=-1)),
                ('notification_id', models.IntegerField(default=-1)),
                ('cn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_work_id', models.CharField(default='', max_length=127)),
                ('work_place_name', models.CharField(max_length=127)),
                ('work_name_type', models.CharField(max_length=255)),
                ('begin', models.CharField(max_length=127)),
                ('end', models.CharField(max_length=127)),
                ('staff_name', models.CharField(max_length=127)),
                ('staff_pNo', models.CharField(max_length=19)),
            ],
        ),
    ]
