# Generated by Django 2.1.5 on 2019-04-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passer',
            name='dt_cn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
