# Generated by Django 2.1.5 on 2019-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_passer_dt_cn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(default=-1)),
                ('minor', models.IntegerField(default=-1)),
                ('passer_id', models.IntegerField(default=-1)),
                ('dt_begin', models.DateTimeField(blank=True, null=True)),
                ('rssi', models.IntegerField(default=-1)),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Beacon_History',
        ),
        migrations.RemoveField(
            model_name='pass_history',
            name='minor',
        ),
        migrations.AddField(
            model_name='beacon',
            name='customer_order_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='beacon',
            name='dt_battery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='dt_install',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='last_passer_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='beacon',
            name='operation_staff_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_id_3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='in_staff_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='out_staff_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='overtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='overtime_staff_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='work_id',
            field=models.CharField(default=-1, max_length=127),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pass_history',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='major',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='work',
            name='minor',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='dt_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='major',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='minor',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pass',
            name='is_in',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pass',
            name='passer_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pass_history',
            name='action',
            field=models.IntegerField(default=0),
        ),
    ]
