# Generated by Django 2.1.5 on 2019-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190507_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass_history',
            name='year_month_day',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
