# Generated by Django 2.1.5 on 2019-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20190509_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dt_begin_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dt_begin_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dt_begin_3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dt_end_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dt_end_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dt_end_3',
        ),
        migrations.AddField(
            model_name='employee',
            name='begin_1',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='employee',
            name='begin_2',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='employee',
            name='begin_3',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_1',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_2',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_3',
            field=models.CharField(default='', max_length=127),
        ),
    ]
