# Generated by Django 2.1.5 on 2019-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190509_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='begin_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='begin_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='begin_3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_id_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_id_3',
        ),
        migrations.AddField(
            model_name='employee',
            name='works',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
