# Generated by Django 2.1.5 on 2019-06-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190607_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passer_id', models.IntegerField()),
                ('employee_id', models.IntegerField(default=-1)),
                ('work_id', models.IntegerField()),
                ('dt_begin', models.DateTimeField()),
                ('dt_end', models.DateTimeField()),
                ('days_total', models.IntegerField()),
                ('days_working', models.IntegerField()),
                ('count_late', models.IntegerField()),
                ('count_leave', models.IntegerField()),
                ('count_over', models.IntegerField()),
            ],
        ),
    ]
