# Generated by Django 2.1.5 on 2019-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('regNo', models.CharField(max_length=127)),
                ('ceoName', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=1024)),
                ('business_type', models.CharField(max_length=1024)),
                ('business_item', models.CharField(max_length=1024)),
                ('dt_reg', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not_Enter', max_length=255)),
                ('contract_no', models.CharField(max_length=33)),
                ('dt_reg', models.DateTimeField(auto_now_add=True)),
                ('dt_accept', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(default=10)),
                ('contractor_id', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=127)),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=127)),
                ('staff_pNo', models.CharField(max_length=19)),
                ('staff_email', models.CharField(max_length=320)),
                ('manager_id', models.IntegerField()),
                ('manager_name', models.CharField(max_length=127)),
                ('manager_pNo', models.CharField(max_length=19)),
                ('manager_email', models.CharField(max_length=320)),
                ('business_reg_id', models.IntegerField()),
                ('dt_payment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(default=-1)),
                ('employee_name', models.CharField(default='unknown', max_length=127)),
                ('pNo', models.CharField(max_length=19)),
                ('pType', models.IntegerField(default=0)),
                ('push_token', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('co_id', models.IntegerField()),
                ('co_name', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
                ('department', models.CharField(max_length=127)),
                ('pNo', models.CharField(max_length=19)),
                ('pType', models.IntegerField(default=0)),
                ('push_token', models.CharField(default='unknown', max_length=255)),
                ('email', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('work_place_id', models.IntegerField()),
                ('work_place_name', models.CharField(max_length=127)),
                ('type', models.CharField(max_length=127)),
                ('contractor_id', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=127)),
                ('dt_begin', models.DateTimeField(auto_now_add=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=127)),
                ('staff_pNo', models.CharField(max_length=19)),
                ('staff_email', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('contractor_id', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=127)),
                ('place_name', models.CharField(max_length=127)),
                ('manager_id', models.IntegerField()),
                ('manager_name', models.CharField(max_length=127)),
                ('manager_pNo', models.CharField(max_length=19)),
                ('manager_email', models.CharField(max_length=320)),
                ('order_id', models.IntegerField()),
                ('order_name', models.IntegerField()),
            ],
        ),
    ]
