# Generated by Django 2.1.5 on 2019-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=127, null=True)),
                ('regNo', models.CharField(max_length=127, null=True)),
                ('ceoName', models.CharField(max_length=127, null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('business_type', models.CharField(max_length=1024, null=True)),
                ('business_item', models.CharField(max_length=1024, null=True)),
                ('dt_reg', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(default='Not_Enter', max_length=255)),
                ('contract_no', models.CharField(blank=True, max_length=33)),
                ('dt_reg', models.DateTimeField(auto_now_add=True)),
                ('dt_accept', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(default=10)),
                ('staff_id', models.IntegerField(default=-1)),
                ('staff_name', models.CharField(max_length=127)),
                ('staff_pNo', models.CharField(max_length=19)),
                ('staff_email', models.CharField(max_length=320)),
                ('manager_id', models.IntegerField(default=-1)),
                ('manager_name', models.CharField(default='', max_length=127)),
                ('manager_pNo', models.CharField(default='', max_length=19)),
                ('manager_email', models.CharField(default='', max_length=320)),
                ('business_reg_id', models.IntegerField(default=-1)),
                ('dt_payment', models.DateTimeField(blank=True, null=True)),
                ('is_contractor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept_work', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('dt_begin', models.DateTimeField(blank=True, null=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('work_id', models.IntegerField()),
                ('employee_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='-----', max_length=127)),
                ('pNo', models.CharField(max_length=19)),
                ('dt_begin_beacon', models.DateTimeField(blank=True, null=True)),
                ('dt_end_beacon', models.DateTimeField(blank=True, null=True)),
                ('dt_begin_touch', models.DateTimeField(blank=True, null=True)),
                ('dt_end_touch', models.DateTimeField(blank=True, null=True)),
                ('overtime', models.IntegerField(default=0)),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.IntegerField(default=-1)),
                ('type', models.IntegerField(default=10)),
                ('corp_id', models.IntegerField(default=-1)),
                ('corp_name', models.CharField(default='None', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('login_id', models.CharField(max_length=128)),
                ('login_pw', models.CharField(max_length=128)),
                ('co_id', models.IntegerField(default=-1)),
                ('co_name', models.CharField(default='unknown', max_length=127)),
                ('position', models.CharField(default='', max_length=127)),
                ('department', models.CharField(default='', max_length=127)),
                ('pNo', models.CharField(default='', max_length=19)),
                ('pType', models.IntegerField(default=0)),
                ('push_token', models.CharField(default='unknown', max_length=255)),
                ('email', models.CharField(default='', max_length=320)),
                ('is_app_login', models.BooleanField(default=False)),
                ('dt_app_login', models.DateTimeField(blank=True, null=True)),
                ('is_login', models.BooleanField(default=False)),
                ('dt_login', models.DateTimeField(blank=True, null=True)),
                ('is_site_owner', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('work_place_id', models.IntegerField()),
                ('work_place_name', models.CharField(max_length=127)),
                ('type', models.CharField(max_length=127)),
                ('contractor_id', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=127)),
                ('dt_begin', models.DateTimeField(blank=True, null=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=127)),
                ('staff_pNo', models.CharField(max_length=19)),
                ('staff_email', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('contractor_id', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=127)),
                ('place_name', models.CharField(max_length=127)),
                ('manager_id', models.IntegerField()),
                ('manager_name', models.CharField(max_length=127)),
                ('manager_pNo', models.CharField(max_length=19)),
                ('manager_email', models.CharField(max_length=320)),
                ('order_id', models.IntegerField()),
                ('order_name', models.CharField(max_length=127)),
                ('x', models.FloatField(default=None, null=True)),
                ('y', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
