# Generated by Django 2.1.5 on 2019-01-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business_reg_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_no',
            field=models.CharField(default='', max_length=33),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contractor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contractor_name',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_email',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_id',
            field=models.IntegerField(verbose_name=-1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_name',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_pNo',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='customer',
            name='staff_id',
            field=models.IntegerField(default=-1),
        ),
    ]
