# Generated by Django 2.1.5 on 2019-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190117_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='login_id',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='staff',
            name='login_pw',
            field=models.CharField(default='happy_day!!!', max_length=55),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_id',
            field=models.IntegerField(default=-1),
        ),
    ]
