# Generated by Django 2.1.5 on 2019-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190117_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='work_place',
            name='order_name',
            field=models.CharField(max_length=127),
        ),
    ]
