# Generated by Django 2.1.5 on 2019-01-30 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190128_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pType',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='push_token',
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_begin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='unknown', max_length=127),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='work_name',
            field=models.CharField(default='unknown', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='work_place_name',
            field=models.CharField(default='unknown', max_length=127),
            preserve_default=False,
        ),
    ]
