# Generated by Django 2.1.5 on 2019-02-08 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190130_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dt_app_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='dt_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='is_app_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='co_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='co_name',
            field=models.CharField(default='unknown', max_length=127),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pNo',
            field=models.CharField(default='', max_length=19),
        ),
    ]
