# Generated by Django 2.1.5 on 2019-02-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190208_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_site_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login_pw',
            field=models.CharField(default='happy_day!!!', max_length=128),
        ),
    ]
