# Generated by Django 2.1.5 on 2019-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20190208_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.IntegerField(default=-1)),
                ('type', models.IntegerField(default=10)),
                ('corp_id', models.IntegerField(default=-1)),
                ('corp_name', models.CharField(default='None', max_length=127)),
            ],
        ),
    ]
