# Generated by Django 2.1.5 on 2019-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_registration',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='business_item',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='business_type',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='ceoName',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='name',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='regNo',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
