# Generated by Django 2.1.5 on 2019-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20190219_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_registration',
            name='customer_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='dt_reg',
            field=models.DateTimeField(blank=True),
        ),
    ]
