# Generated by Django 2.1.5 on 2019-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20190219_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='corp_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contractor_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contractor_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_no',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
