# Generated by Django 2.1.5 on 2019-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20190219_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_registration',
            name='dt_reg',
            field=models.DateTimeField(default=None),
        ),
    ]
