# Generated by Django 2.1.5 on 2019-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20190219_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_registration',
            name='dt_reg',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
