# Generated by Django 2.1.5 on 2019-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20190219_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_registration',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='business_item',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='business_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='ceoName',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='business_registration',
            name='regNo',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
