# Generated by Django 2.1.5 on 2019-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20190219_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_place_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_begin_beacon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_begin_touch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_end_beacon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_end_touch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='work_place',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='work_place',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='성함을 넣어주세요.', max_length=127),
        ),
    ]
