# Generated by Django 2.1.5 on 2019-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20190224_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_accept_work',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
