# Generated by Django 2.1.5 on 2019-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_employee_is_accept_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='이름', max_length=127),
        ),
    ]
