# Generated by Django 2.1.5 on 2019-03-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20190225_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='-----', max_length=127),
        ),
    ]
