# Generated by Django 2.1.5 on 2019-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20190309_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dt_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dt_app_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dt_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login_pw',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='work',
            name='dt_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
