# Generated by Django 2.1.5 on 2019-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20190507_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
